{{- if and .Values.Datacenter.Enabled (not .Values.Persistence.DatacenterExistingClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-datacenter-pvc
  labels:
{{- include "bitbucket-chart.labels" . | indent 4 }}
spec:
  accessModes: [ {{ .Values.Persistence.DatacenterVolumeClaimTemplates.AccessModes | quote }} ]
  resources:
    requests:
      storage: {{ .Values.Persistence.DatacenterVolumeClaimTemplates.Storage | quote }}
  {{- if .Values.Persistence.DatacenterVolumeClaimTemplates.StorageClassName }}
  {{- if (eq "-" .Values.Persistence.DatacenterVolumeClaimTemplates.StorageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.Persistence.DatacenterVolumeClaimTemplates.StorageClassName }}"
  {{- end }}
  {{- end }}
  {{- if .Values.Persistence.DatacenterVolumeClaimTemplates.Selector.Enabled }}
  selector:
    matchLabels:
      {{- range $key,$value := .Values.Persistence.DatacenterVolumeClaimTemplates.Selector.MatchLabels }}
      {{ $key }} : {{ $value }}
      {{- end }}
    {{- end }}
{{- end -}}
