{{- if .Values.Service.SshNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
  {{- include "bitbucket-chart.labels" . | indent 2 }}
    serviceType: ssh

  annotations:
  {{- range $key, $value := .Values.Service.Annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: 7999
      name: bitbucket-ssh-port
      targetPort: 7999
      protocol: TCP


  type: NodePort

  selector:
    app: {{ .Release.Name }}
{{- end }}    
