{{- if .Values.SshService.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
  {{- include "bitbucket-chart.labels" . | indent 2 }}
    serviceType: ssh

  annotations:
  {{- range $key, $value := .Values.SshService.Annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: 7999
      name: bitbucket-ssh-port
      targetPort: 7999
      protocol: TCP
      {{- if and (eq .Values.SshService.Type "NodePort") .Values.SshService.NodePort }}
      nodePort: {{ .Values.SshService.NodePort }}
      {{- end }}

  type: {{ .Values.SshService.Type }}
  {{- if and (eq .Values.SshService.Type "LoadBalancer") .Values.SshService.LoadBalancerIP }}
  loadBalancerIP: {{ .Values.SshService.LoadBalancerIP }}
  {{- end }}

  selector:
    app: {{ .Release.Name }}
{{- end }}    
