version: 2
jobs:
    build-and-publish:
      docker:
        - image: praqma/helm-aws:2.14.1
      steps:
        - checkout
        - run: .circleci/build.sh publish
    build:
      docker:
        - image: praqma/helm-aws:2.14.1
      steps:
        - checkout
        - run: .circleci/build.sh 

workflows:
  version: 2
  build:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              ignore: master